### PR TITLE
Import lxd-agent-source from LP

### PR DESCRIPTION
**Pull request by MusicDin**
This PR is an initial commit which just import source as is from LP.

Source: https://launchpad.net/ubuntu/+source/lxd-agent-loader

### CODE REVIEW

**Comment by simondeziel** [comment]
> Source: https://launchpad.net/ubuntu/+source/lxd-agent-loader

Since we are relocating the "upstream", have we started the discussion with the server/CPC teams as they will need to pull from here from now on.

**Comment by MusicDin** [comment]
I think this is next step, after we make this repo ready

**Comment by tomponline** [comment]
Ah John Chitturn couldn't find an upstream repo and stephane said there wasnt one, but if there is one in launchpad afterall then we don't need this one.

**Comment by tomponline** [comment]
"Stéphane Graber:
There's no git repo for lxd-agent-loader

It's just a basic source tarball"

**Comment by simondeziel** [comment]
Indeed, https://code.launchpad.net/ubuntu/+source/lxd-agent-loader seems to be the work of the automatic import by `git-ubuntu`.

**Comment by tomponline** [comment]
The process of getting it into Ubuntu isn't clear to me yet but we will discuss with john further as planned

**Comment by MusicDin** [comment]
@tomponline Can this be merged, so that I can rebase another PR? Or is there anything to change?

**Pull request closed without merging**
